### ISSUE TITLE
Do componets also connect to .NET api

### ISSUE THREAD

**Issue by weedkiller** [mephisto83/redquickbuilder#18]
Hey the idea is very cool, would be nice to have the backend in .NET 5 flushed out a little more

**Comment by mephisto83** [comment]
Yeah, the frontend and the backend are generated at the same time. So there is a .net core backend generated also. A few weeks ago I transitioned it to a .NET 5. The plan is to always keep to the latest major version, until I find a reason not to do that. I'm planning on doing a series of videos to try to explain what I am trying to do and what I have done. Also, I want to make a few repositories with the generated output.

**Comment by weedkiller** [comment]
Awesome... I was following a little, I found it while search for a way to build views frontend quicker, a summary of how to use it or video will help 👍 

IMHO - focusing on the web and transitioning to other/mobile would allow you to plan your time wisely.
